### ISSUE TITLE
la fecha del 18 Marzo esta mal puesta

### ISSUE THREAD

**Issue by superegi** [ivanMSC/COVID19_Chile#1]
Hola

soy nuevo en esto de la programación.  

veo que en tu BD las entradas del 18 Marzo están en distinto orden que las previas (%d-%m-%Y vs %m-%d-%Y).

saludos
![imagen](https://user-images.githubusercontent.com/50183741/77028985-320ea000-6979-11ea-872c-30c25eb91815.png)

**Comment by ivanMSC** [comment]
Toda la razón! Arreglado!
Gracias

**Comment by superegi** [comment]
Gracias
Saludos
Podemos conversar?
hight.esnif@gmail.com
