### ISSUE TITLE
Posible error en obtener los casos totales en el archivo covid19_comunas.csv

### ISSUE THREAD

**Issue by EnzoAndree** [ivanMSC/COVID19_Chile#10]
Hola Ivan, Felicidades por este Repositorio.

Quería comentarte que tal vez pueda existir un error en los datos de la región de O'Higgins. En el archivo `covid19_comunas.csv` figura con 0 casos, sin embargo, el `covid19_chile.csv` está el numero de casos correctos.

Saludos!

**Comment by ivanMSC** [comment]
Hola @EnzoAndree ! Gracias! En qué fecha?

**Comment by EnzoAndree** [comment]
De hecho, en todas las fechas sale 0 casos

**Comment by ivanMSC** [comment]
@EnzoAndree  Podrías subir una imagen?

**Comment by ivanMSC** [comment]
Yo no veo el problema.

![Screenshot_20200413-140213](https://user-images.githubusercontent.com/35350256/79145914-7716ce00-7d8f-11ea-9501-1a154775b948.png)

**Comment by EnzoAndree** [comment]
Es en el archivo `covid19_comunas.csv`

![ohi01](https://user-images.githubusercontent.com/875732/79146045-b1806b00-7d8f-11ea-84a9-edf7c664b0b5.png)

**Comment by ivanMSC** [comment]
@EnzoAndree Ah! O'Higgins es una comuna de Aysén jeje

Solo hay un choque de nombres

**Comment by EnzoAndree** [comment]
O por Dios!.

Todo Ok entonces!
