### ISSUE TITLE
Rectificar Info en readme

### ISSUE THREAD

**Issue by MinCiencia** [ivanMSC/COVID19_Chile#12]
Hola, con repecto a el archivo readme en este repo:

> Tiene algunos problemas, por ejemplo, no reportan el número de casos por cumuna si el número de casos es menor a 4 (lo que hago yo para rellenar la información es multiplicar la tasa por la población y redondear); no entregan el número de recuperados y muertos por comuna, etc. Mientras no se solucionen esos problemas, seguiré manteniendo el archivo en la medida que se publique más información.

Actualmente sí se reporta por comuna para casos con menos de 4. En los próximos días agregaremos la información que resulta de la investigación epidemiológica por comuna que concluye casos actuales , activos y fallecidos.

**Comment by ivanMSC** [comment]
Muchas gracias!! 

> En los próximos días agregaremos la información que resulta de la investigación epidemiológica por comuna que concluye casos actuales , activos y fallecidos

Eso estaría buenísimo!!
