### ISSUE TITLE
Regresión del Gráfico de total de casos confirmados

### ISSUE THREAD

**Issue by naoliden** [ivanMSC/COVID19_Chile#13]
Hola,
Si es posible quisiera saber cómo llegaste a la fórmula que expones en la sección de "Gráfico de total de casos confirmados" y cómo hiciste para ajustar los parámetros. Estoy estudiando estadística y quisiera aprender a hacer lo que hiciste. Podrías ayudarme o darme alguna pista para leer por ahí?

**Comment by ivanMSC** [comment]
Hola @naoliden,
La fórmula es una generalización de la exponencial que está a medio camino de una curva logística. Si te fijas,  con `b2=0` obtienes una exponencial común, mientras que con `b1=b2` obtienes una curva de tipo logística o sigmoidal.  La formula se construye pensando en una función cuyo logaritmo tenga derivada sigmoidal. Es decir, el logaritmo de la curva de casos confirmados tiene una pendiente inicial que varía continuamente hasta, en teoría, una pendiente final.  delta es un parámetro que controla la suavidad de la transición.

El ajuste se hace con mínimos cuadrados en el espacio log-lineal, asignando a cada punto un peso proporcional al dato en espacio lineal. Esto permite ajustar bien los datos menores sin descuidar los datos mayores.

Aquí te dejo una animación de la evolución de la regresión para los últimos 14 días.

![validation](https://user-images.githubusercontent.com/35350256/79698321-3a971680-8256-11ea-8aca-a8e254c4dc16.gif)

Para todo esto ocupo MATLAB. Para más información sobre los intevalos de confianza lee [esta documentación ](https://la.mathworks.com/help/curvefit/confidence-and-prediction-bounds.html)
