### ISSUE TITLE
Inferencia de muertos?

### ISSUE THREAD

**Issue by jorgeperezrojas** [ivanMSC/COVID19_Chile#14]
Hola Iván, otra vez gracias por toda la pega.

Vi que en las visualizaciones tienes un número de muertos por comunas que infieres desde los otros datos. Lo haces aprovechándote de la forma de calcular recuperados del Minsal? me interesa mucho tener ese dato e iba a hacerlo así, pero quería saber si tu ya lo habías calculado para saber tu opinión de qué tan ruidoso puede ser. Busqué el dato acá pero no lo encontré (solo lo vi en la visualización). 

Muchas gracias otra vez y gran pega!

**Comment by ivanMSC** [comment]
Lo que hago es restar las  columnas casos actuales y casos activos. El numero da los fallecidos cuyos sintomas iniciaron o que fueron confirmados hace menos de 14 dias. Por lo tanto, espero poder actualizar la cifra para el reporte del proximo lunes (cuando se cumplen 2 semanas del primer EPI con este formato).

No lo tengo publicado porque no puedo garantizar que el número sea el correcto.

Tal vez se puede usar la información de las otras columnas para inferir los casos fallecidos con mejor resolución. No lo he pensado, ni he mirado los datos. Cuéntame si descubres algo!

**Comment by jorgeperezrojas** [comment]
Sí, estaba mirando que en algunas comunas el dato es menos ruidoso si usas la SE-1 y SE-2 (las dos semanas epidemiológicas anteriores). Pero hay tanto error chico que igual es ruidoso.

A la tarde/noche trataré de procesar los datos a ver si al menos las sumas calzan. Saludos!
