### ISSUE TITLE
Si es posible corregir.

### ISSUE THREAD

**Issue by claudioespinosaparra** [ivanMSC/COVID19_Chile#16]
Sale en reporte del día 26 de abril para la comuna de Alto Hospicio:

Fecha | CUT | Region | Comuna | Confirmados Acumulados | Nuevos   Confirmados
26-04-2020 | 1107 | TA | Alto Hospicio | 51 | 6

Debe decir:
Fecha | CUT | Region | Comuna | Confirmados Acumulados | Nuevos   Confirmados
26-04-2020 | 1107 | TA | Alto Hospicio | 52 | 7

Saludos y muchas gracias por vuestro trabajo.

**Comment by ivanMSC** [comment]
Hola @claudioespinosaparra
Te puedo preguntar, cuál es tu fuente? En el twitter del Gobierno Regional dice que fueron 6 casos nuevos en Alto Hospicio https://twitter.com/Gore_Tarapaca/status/1254455652677832707/photo/1

**Comment by claudioespinosaparra** [comment]
Noticia del día de ayer:

A 156 casos de Covid-19 llega la Región de Tarapacá
Ayer Se confirmaron 13 nuevos contagios hasta las 21 horas de ayer sábado.

(Agencia Uno)
(Agencia Uno)
Un total de 13 nuevos casos de Covid-19 tiene la Región de Tarapacá, según la actualización del Ministerio de Salud, hasta ayer a las 21 horas. Con esto, suman 156 contagios desde el primer paciente infectado hace 36 días.
El intendente Miguel Ángel Quezada sostuvo durante el reporte diario, que se trata de seis hombres y siete mujeres, de los cuales siete viven en Iquique y seis en Alto Hospicio.
Del total regional de pacientes contagiados, 89 son hombres y 67 son mujeres y con respecto a su lugar de residencia, 70 son de Iquique, 52 de Alto Hospicio, 32 de Pica y dos de Pozo Almonte.
En relación a los hospitalizados, dos están en la Unidad de Cuidados Intensivos y cuatro en las camas básicas del Hospital Regional.
Hasta la fecha, se han realizado 2.473 exámenes, 1.969 arrojaron negativos y 348 están a la espera de los resultados.


Fuente: soychile.cl - https://www.soychile.cl/Iquique/Sociedad/2020/04/26/650557/A-156-casos-de-Covid19-llega-la-Region-de-Tarapaca.aspx

Y hoy infomar 6 casos más y da 58 en total para la comuna de Alto Hospicio.

Trataré de ubicar otra fuente. si es posible. saludos

**Comment by ivanMSC** [comment]
Ah, ya. En esa noticia dice que fueron 6 nuevos en alto hospicio el dia 26 de abril. Entonces, el problema viene de antes parece. Buscaré en los reportes anteriores donde está el error.

**Comment by ivanMSC** [comment]
@claudioespinosaparra Se hizo la corrección. Se modificó los números de Iquique que también tenían error. Muchas gracias!
