### ISSUE TITLE
Actualización 2020-04-28 COVID19_Chile/covid19_comunas_informeEpidemiologico.csv

### ISSUE THREAD

**Issue by elaval** [ivanMSC/COVID19_Chile#17]
Hola Ivan,

Hace poco actualizaron el informe epidemiológico del 28 de Abril

https://cdn.digital.gob.cl/public_files/Campa%C3%B1as/Corona-Virus/Reportes/INFORME_EP_COVID19_20200428.pdf

Pero al parecer no se ha actualizado en tu repositorio ¿habrá algún cambio en el formato? ¿estará en su día libre el bot ;-)?

Saludos y gracias por este muy importante recurso!!

**Comment by esteblock** [comment]
Hola! en https://github.com/YachayData/COVID-19/ también importamos los informes epidimiológigos de este repositorio :)
Estamos dispuestos a ayudar con el código para la mantención si es necesario.
Saludos!

**Comment by ivanMSC** [comment]
@elaval @estebaniglesias fe97346

En el pdf, cambió de nombre la comuna de Concón a Con Con 😂

Necesito buscar una función de comparación difusa para Google Apps Script (javascript) 😁

**Comment by elaval** [comment]
Gracias!
