### ISSUE TITLE
Al parecer se intercambiaron los datos en algunas regiones 2020-05-04

### ISSUE THREAD

**Issue by elaval** [ivanMSC/COVID19_Chile#20]
![image](https://user-images.githubusercontent.com/68602/80982723-b3bb6f80-8df9-11ea-9b44-adef048314fc.png)
 Total de casos de la Metropolitana aparece en Valparaíso (y lo mismo con otras regiones)

**Comment by ivanMSC** [comment]
@elaval El alumno en practica que digita en el minsal tiene dedos gordos
