### ISSUE TITLE
Informe epidemiológico 2020-05-04?

### ISSUE THREAD

**Issue by elaval** [ivanMSC/COVID19_Chile#21]
Disculpa que te moleste @ivanMSC  ... pero eres víctima de tu éxito (y algunos nos hemos hecho dependientes de tu datos que generalmente se actualizan de manera muy oportuna)

Algún ETA para actualizar los datos comunales del último informe epidemiológico?

Gracias!!

**Comment by ivanMSC** [comment]
@elaval JAJA paciencia. Me cuesta confiarle el EPI a un bot. Siempre aparecen imprevistos que hace que se caiga. Por eso, tengo que hacerlo de forma supervisada. En unos minutos lo actualizo.

**Comment by ivanMSC** [comment]
@elaval Listo.
