### ISSUE TITLE
falta registro del 2 / Mayo en Biobío

### ISSUE THREAD

**Issue by elaval** [ivanMSC/COVID19_Chile#24]
Hola @ivanMSC,

Hoy me percaté que en los datos históricos de comunas en Biobío no aparece el registro del 2 de mayo.  No estoy segura si es un issue nuevo o es algo que no lo había notado antes.

Hoy, al comparar con datos de una semana atrás se generó una excepción en mi código

Si es algo simple, sería bueno arreglarlo, si no ... dar el aviso para manejar la excepción en el frontend.

Saludos

@elaval

![image](https://user-images.githubusercontent.com/68602/81489420-22a62780-9243-11ea-956e-af5c6ad65900.png)

**Comment by ivanMSC** [comment]
Hola @elaval

Commit 9150187

Simplemente, no existe data para el día 2 de mayo en la región del Biobío. [La prensa local armó la grande](https://elcontraste.cl/sabado-02-de-mayo-el-dia-que-la-seremi-de-salud-no-informo-como-corresponde/02/05/2020/) y al día siguiente todo volvió a la normalidad.

**Comment by elaval** [comment]
Gracias!
