### ISSUE TITLE
Consula actualización comunal 15 Mayo

### ISSUE THREAD

**Issue by Orlando-GIS** [ivanMSC/COVID19_Chile#26]
Hola Ivan,

habrá actualización covid comunal hoy?

Saludos

**Comment by ivanMSC** [comment]
Pasa que a veces los Seremi demoran en entregar la información.

A partir de esta semana haré lo siguiente: Entre 13:00 y 14:00 subiré la información que haya hasta ese momento del día. Luego durante el día subiré una segunda actualización, una vez que todos los organismos regionales se hayan pronunciado.

**Comment by Orlando-GIS** [comment]
Muchas gracias Ivan
