### ISSUE TITLE
consulta datos comunales 27-05

### ISSUE THREAD

**Issue by Orlando-GIS** [ivanMSC/COVID19_Chile#27]
Hola Ivan

No se han refrescado los datos de las comunas de hoy, en el archivo historial_comunas.csv pero veo que la información está en tu panel interactivo.
¿Se seguirá actualizando esta planilla?

Saludos 

Orlando

**Comment by ivanMSC** [comment]
Se me olvidó mandar el commit a las 14:00 😂
ya está actualizado

**Comment by Orlando-GIS** [comment]
Vale, muchas gracias
