### ISSUE TITLE
Actulización diaria historial_comunas.csv

### ISSUE THREAD

**Issue by Orlando-GIS** [ivanMSC/COVID19_Chile#29]
Hola @ivanMSC 

Saben ustedes si el MinSal va a seguir reportando la información que compilas en el archivo historial_comunas.csv. cerca de medio día? Pensé que el retraso de ayer se debía, justamente al cambio de criterio, pero hoy nuevamente se está repitiendo el retraso en la entrega de la publicación de los datos. 
Saludos 
Orlando

**Comment by ivanMSC** [comment]
Pasó algo raro. Se subió un archivo sin los datos de hoy a las 14:03.

Ahora lo reparé. Gracias por avisar.

 Luego se subirá la información de regiones faltantes.

**Comment by Orlando-GIS** [comment]
Vale, gracias
