### ISSUE TITLE
Integración de dataset latinoamerica

### ISSUE THREAD

**Issue by pablodz** [ivanMSC/COVID19_Chile#3]
Hola, junto con una organización sin fines de lucro se está tratando de centralizar la información de contagiados/muertos/recuperados covid-19 y estamos buscando un encargado por país. En tu caso Chile.
El formato del csv se está manejando acorde al formato global https://github.com/CSSEGISandData/COVID-19 para luego poder juntar la data.
Esto comprende las siguientes columnas: 
![image](https://user-images.githubusercontent.com/28235457/77130645-c4b94880-6a26-11ea-8a6f-77f757d665d1.png)
Podrías comentarme si estás interesado en aportar porfavor.
El dataset centralizado se propone en este repositorio: https://github.com/DataScienceResearchPeru/covid-19_pe

**Comment by ivanMSC** [comment]
Me gustaría ayudar. Indícame cómo proceder. 
Una cosa: En Chile, el gobierno no ha publicado datos a nivel de `Province/State` para casos `Recovered`. Esto puede ser un problema.

**Comment by pablodz** [comment]
> Me gustaría ayudar. Indícame cómo proceder.
> Una cosa: En Chile, el gobierno no ha publicado datos a nivel de `Province/State` para casos `Recovered`. Esto puede ser un problema.

Gracias por tu interés. Claro, eso ya se va coordinando. Ahora mismo estoy viendo cómo poner la data para que sea compatible con la data global. Me contactaré por aquí para informarte sobre cómo quedaría la estructura.
