### ISSUE TITLE
Actulización diaria historial_comunas.csv I y II Región

### ISSUE THREAD

**Issue by Orlando-GIS** [ivanMSC/COVID19_Chile#30]
Hola @ivanMSC 

Aún está pendiente la actualización de la I y II región de hoy, ¿habrá faltado algo?

Saludos 

Orlando

**Comment by ivanMSC** [comment]
Hola @Orlando-GIS
A la hora de subida de la actualización, esas regiones aún no entregaban los datos.

En unos momentos subiré los datos de las regiones faltantes.
