### ISSUE TITLE
Error in dates

### ISSUE THREAD

**Issue by frmco** [ivanMSC/COVID19_Chile#31]
![image](https://user-images.githubusercontent.com/64239643/85049067-3b6afc80-b162-11ea-981a-0e1aa36a167c.png)

**Comment by frmco** [comment]
I suppose that the bot move the columns.

**Comment by frmco** [comment]
Reopen comment. I'm sorry for the spam.

**Comment by frmco** [comment]
Fixed up.

**Comment by ivanMSC** [comment]
La tabla del ministerio agregó una nueva columna que confundió al bot. Deberia estar resuelto ahora.
