### ISSUE TITLE
Error en nuevos casos

### ISSUE THREAD

**Issue by frmco** [ivanMSC/COVID19_Chile#32]
Son 119 nuevos casos en el Maule.
![image](https://user-images.githubusercontent.com/64239643/89719327-29088480-d995-11ea-8e8d-b5474c443317.png)

**Comment by ivanMSC** [comment]
@frmco Ayer se reportaron 9.639 casos acumulados en el Maule. Hoy tenemos 9.755.

![Screenshot_20200808-174004.png](https://user-images.githubusercontent.com/35350256/89720281-39712d00-d99e-11ea-97b5-bdd0a12401ef.png)
