### ISSUE TITLE
Problema con el df nuevos comunas

### ISSUE THREAD

**Issue by luispsa** [ivanMSC/COVID19_Chile#34]
Hola ivanMSC

Primero que nada, gracias por poner a disposición datos sobre el covid19 en chile, a lo que voy, estuve jugando con los datos de los csv sobre comuna, en la de totales, hay algunas comunas que están duplicadas y en el csv de historial_comunas.csv la columna fecha tiene datos para meses de noviembre y diciembre de este año, favor chequear

sl2

**Comment by ivanMSC** [comment]
@luispsa Hola.

Porfa indicar ejemplo. En qué archivo y línea se encuentra el error?

**Comment by luispsa** [comment]
Hola,
cuando cargué con pd.read_csv  "covid19_comunas_informeEpidemiologico.csv" , pillé algunas comunas duplicadas (por ej aysén salía también como "aisén"  o "calera" con "la calera") no sé si hay otras pq no seguí buscando

En historial_comunas.csv al pivotear los datos, salen fecha de noviembre/diciembre de este año

**Comment by ivanMSC** [comment]
Hola @luispsa 

Se estandarizaron los nombres de las comuna en el historial del informe epidemiológico. 

Respecto a las fechas de noviembre y diciembre, no veo lo que tú. Considera que el formato es dd-mm-yyyy. Este es el resultado de aplicar List.Max con PowerQuery sobre la columna de fechas.

![IMG_20201006_222801_832.jpg](https://user-images.githubusercontent.com/35350256/95277044-37530f80-0823-11eb-80cd-8c55e0f6ec41.jpg)

Gracias

**Comment by luispsa** [comment]
> Hola @luispsa
> 
> Se estandarizaron los nombres de las comuna en el historial del informe epidemiológico.
> 
> Respecto a las fechas de noviembre y diciembre, no veo lo que tú. Considera que el formato es dd-mm-yyyy. Este es el resultado de aplicar List.Max con PowerQuery sobre la columna de fechas.
> 
> ![IMG_20201006_222801_832.jpg](https://user-images.githubusercontent.com/35350256/95277044-37530f80-0823-11eb-80cd-8c55e0f6ec41.jpg)
> 
> Gracias

Ok, voy a chequear pasa que dejo que pandas asigne el formato a la fecha, al menos con los csv del minciencias andan bien.

Sl2

**Comment by luispsa** [comment]
> > Hola @luispsa
> > Se estandarizaron los nombres de las comuna en el historial del informe epidemiológico.
> > Respecto a las fechas de noviembre y diciembre, no veo lo que tú. Considera que el formato es dd-mm-yyyy. Este es el resultado de aplicar List.Max con PowerQuery sobre la columna de fechas.
> > ![IMG_20201006_222801_832.jpg](https://user-images.githubusercontent.com/35350256/95277044-37530f80-0823-11eb-80cd-8c55e0f6ec41.jpg)
> > Gracias
> 
> Ok, voy a chequear pasa que dejo que pandas asigne el formato a la fecha, al menos con los csv del minciencias andan bien.
> 
> Sl2

update: con to_datetime especifique la fecha ,ahora pandas lo carga y pivotea bien

grax

Luis

**Comment by ivanMSC** [comment]
@luispsa perfecto
