### ISSUE TITLE
Outlier 17 de junio

### ISSUE THREAD

**Issue by LuisAcunaSM** [ivanMSC/COVID19_Chile#36]
Hola. El 17 de junio registra, al menos para la RM, una alza desmesurada que la convierte en _outlier_: 32.230 casos `Nuevo Confirmado` (observación 1.809). ¿Obedece a un problema en el registro de las entidades informantes?
Agradecido, @LuisAcunaSM

**Comment by ivanMSC** [comment]
Ese día se hizo el gran ajuste por parte del ministerio. Fue un caos y una vergüenza nacional. Debiste estar ahi.

**Comment by ivanMSC** [comment]
@LuisAcunaSM Ese día se hizo el gran ajuste por parte del ministerio. Fue un caos y una vergüenza nacional. Debiste estar ahi.

**Comment by ivanMSC** [comment]
Te dejo una noticia al respecto
https://www.epicentrochile.com/2020/07/14/contraloria-instruye-sumario-al-minsal-por-inconsistencias-en-cifras-de-contagios-de-covid-19/

**Comment by LuisAcunaSM** [comment]
Dios... o sea que hay que trabajarlo como excepción excluyéndolo o imputando. Gracias, @ivanMSC , haces un gran trabajo. Agarré de nuevo las estadísticas COVID y lo primero que hice fue el pull de aquí. Muchas gracias.

**Comment by ivanMSC** [comment]
Repartelo en los dias anteriores proporcional a la cantidad de cada dia. O bien usa las series corregidas del ministerio de ciencias. En este repo solo estoy publicando la foto día a día sin reajustes posteriores.

**Comment by LuisAcunaSM** [comment]
👍🏻
