### ISSUE TITLE
Casos nuevos sin ajuste histórico

### ISSUE THREAD

**Issue by adinamarca** [ivanMSC/COVID19_Chile#38]
¡Hola @ivanMSC !

Gracias por tu enorme trabajo. Quería consultarte lo sgte., [sucede que, los casos nuevos contemplan el ajuste histórico](https://github.com/ivanMSC/COVID19_Chile/blob/master/covid19_chile.csv), lo que ocasiona que no calcen con los que reporta, diariamente, el Ministerio de Salud en sus informes.

¿Es posible añadir una columna que brinde el dato del ajuste histórico? De esa forma, cualquier persona que requiera de los casos nuevos con o sin el ajuste, le serviría (en mi caso, lo requiero sin el ajuste histórico).

Nuevamente, gracias por tu gran labor.

Saludos

**Comment by ivanMSC** [comment]
Hola @adinamarca 
Entiendo. No he revisado, pero no están esos datos en el ministerio de ciencias?

**Comment by adinamarca** [comment]
Hola @ivanMSC, ¡sí! Están.
Es solo que, me interesaba ocupar tu repositorio dado que, registra los datos desde Gore o Seremi por comuna de forma diaria. En cambio, si utilizara solo el reporte epidemiológico, se dispone de menor frecuencia de actualización.

Lamentablemente, el repositorio del Ministerio de Ciencia no dispone aún de esta actualización diaria por comuna, por lo que solo disponen los datos comunales del reporte epidemiológico (sin intención de menospreciar el enorme trabajo que ellos realizan). Sin embargo, también abriré un issue en su repositorio (para saber si es posible tener el seguimiento diario por comuna como el que realizas).

Saludos y muchas gracias por la respuesta!

**Comment by ivanMSC** [comment]
@adinamarca hay alguna dificultad en usar el archivo de datos comunales de este repo y para todo lo demas usar lo que ofrece el ministerio de ciencias?

**Comment by adinamarca** [comment]
Creo existían ciertas diferencias entre ambas cifras, aunque, posiblemente se debe a la contabilización de casos por comuna desconocida o no. Pero, en general no, ¡gracias!
