### ISSUE TITLE
Colaboración data

### ISSUE THREAD

**Issue by Marq91** [ivanMSC/COVID19_Chile#4]
Hola que tal! estoy desarrollando una aplicación frontend en React para desplegar info sobre el covid 19 y tu data es la mas accesible que he encontrado ya que los pdf en el sitio Ministerio no tengo como manejarlos, no hay problema si te referencio en mi app como fuente de datos?

También quería colaborar si te interesa a transformar esa data en otro formato como json, para los desarrolladores nos es mas manejable también.

**Comment by ivanMSC** [comment]
Por su puesto! adelante!
