### ISSUE TITLE
Warning: Formato del archivo principal ha sido reemplazado

### ISSUE THREAD

**Issue by ivanMSC** [ivanMSC/COVID19_Chile#5]
En vista de que el gobierno no ha provisto los datos como nos gustaría, he decidido abandonar el formato con el que comencé este repositorio. Próximamente, el archivo cambiará su estructura para dejar de incluir columnas vacías y sin sentido, como coordenadas y centros de salud.

**Comment by ivanMSC** [comment]
Changes deployed 9e40ae0

**Comment by EdlongR** [comment]
Ivan, te felicito por tu trabajo, me dejó con la boca abierta. 
Tu tabla de proyeccion logistica....impresionante.
Sera posible que esta tabla se pueda expandir hasta mayo...?

**Comment by ivanMSC** [comment]
@EdlongR Hola! Muchas gracias! Sobre la proyección, el modelo logístico es uno de los más básicos para estimar la propagación de epidemias y hay que ser muy cauteloso con él. La proyección no la pongo a más de 7 días en el futuro porque a más días, el intervalo de confianza (que puedes ver con las líneas grises) crece demasiado. No es posible estar seguros de una predicción tanto tiempo en el futuro.

De todas maneras, si te interesa saber, el modelo logístico hasta el momento predice con 95% de confianza que para mayo habrán entre 6000 y 16000 casos confirmados en Chile. No dice mucho.

**Comment by EdlongR** [comment]
Ivan, no soy bueno es esto, pero algo comprendo , poco pero algo. 
Estoy llevando mis datos en un excel por el momento, y a lo que tu le llamas Básico, simplemente no logro formularlo en mi cabeza ignorante, para poder expandir tu proyección logística.
Tengo muy presente, que hay que ser extremadamente cauteloso con la información respecto a este tema.
Si me puedes ayudar, seria maravilloso.
De antemanos Gracias

**Comment by ivanMSC** [comment]
@EdlongR Si manejas excel, no tendrás problemas para seguir [este tutorial](https://www.youtube.com/watch?v=Ewp5CF5ba_w)

**Comment by EdlongR** [comment]
Vale, super util, muchas gracias
