### ISSUE TITLE
Datos de comunas: fiabilidad de updates

### ISSUE THREAD

**Issue by javierconcha** [ivanMSC/COVID19_Chile#6]
Excelente trabajo Ivan!

He creado el siguiente mapa interactivo:
[https://github.com/javierconcha/covid-19-Chile](https://github.com/javierconcha/covid-19-Chile)

Leyendo tus comentarios, me sentí identificado con la frustración de no tener más datos oficiales y en un formato mas readable, ademas de los recuperados por regiones. 

Algunos usuarios me han preguntado si es posible hacer un desglose por comuna, y encontré tu repo. Sé que los datos no son reportadas en forma constante, pero mi pregunta es si tienes pensado actualizar los datos en forma constante, una vez que estén disponible?

PS: me encanto tu icono de comprame un café, como lo hiciste? Html? :)

**Comment by ivanMSC** [comment]
Hola @javierconcha no se si te diste cuenta, pero ahora el ministerio de ciencia tiene [un repo](https://github.com/MinCiencia/Datos-COVID19). En la carpeta producto1 tiene los datos historicos por comuna desde el 30 de marzo.

El logo lo hice en paint. xd

**Comment by ivanMSC** [comment]
Sobre los tiempos, intento actualizar el archivo por comunas apenas aparece un informe epidemiológico nuevo. Tengo un bot mirando la pagina del minsal y me avisa cuando hay un documento nuevo. Convierto las tablas del pdf a csv usando Tabula, así que no toma mucho tiempo.

No sé si lo hago más rápido que el repo del MinCiencia

**Comment by javierconcha** [comment]
Ok. Gracias por la info!
