### ISSUE TITLE
Anuncio: Historial de casos por comuna y actualización diaria

### ISSUE THREAD

**Issue by ivanMSC** [ivanMSC/COVID19_Chile#9]
He subido una serie de datos histórica de los casos confirmados por comuna en el archivo `historial_comunas.csv`. El historial de las regiones Arica y Parinacota, Tarapacá, Atacama, Antofagasta, Coquimbo, Valparaíso, O'Higgins, Ñuble, Biobío, Los Ríos, Los Lagos, Aysén y Magallanes se encuentra completo.  Estos datos han sido recopilados de los comunicados oficiales de gobiernos regionales, seremis e intendencias.

De la región Metropolitana solo se dispone de los datos entregados en el informe epidemiológico para días lunes, miércoles y viernes, sin datos históricos antes del 30 de marzo. 

Las demás regiones (Maule, ~~Ñuble~~ y Araucanía), si alguien tiene los datos anteriores al 29 de marzo, agradeceré colaborar! De todas formas yo sigo buscando.

**Comment by LuisAcunaSM** [comment]
Don @ivanMSC nuevamente le agradezco su repositorio. Permítame desahogarme, por favor, no soy un experto en ciencia de datos pero: ¿cómo cresta los repositorios oficiales se implementan con planillas tan mal conformadas? A diferencia de los suyos, los ficheros csv oficiales están mal hechos, con las fechas de series temporales dispuestas en filas, con datos categóricos mal interpuestos. Realmente me sorprende, no sólo me enoja hacer transposición de datos y perder tiempo en tareas tan evitables... Y no digo nada allá o se les ocurriría cambiar los ficheros a medio camino o hacer veinte subdirectorios más con planillas procesadas.

**Comment by ivanMSC** [comment]
Gracias por su comentario. 

Me da la impresión que disponen los datos de esa forma para que sea evidente de la tabla, por ejemplo, el crecimiento a nivel regional de los casos. Eso está mal porque **los datos son para usarlos y no para mirarlos**.

Si no tiene animo de escribirles, creo que vi por ahí un repositorio donde arreglaban los datos oficiales en un formato como la gente. Le aviso si lo encuentro, porque no creo haberlo guardado.
